// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4vGfQQlBs3BLelaaghVkaIccn6xS-GTk',
    appId: '1:183089429196:web:6d6bd538d95b602186e069',
    messagingSenderId: '183089429196',
    projectId: 'ncuber',
    authDomain: 'ncuber.firebaseapp.com',
    storageBucket: 'ncuber.appspot.com',
    measurementId: 'G-FGVELNX25C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAtv9HPvdWj9Qe1yP9qMYddiqXhdV8PPk',
    appId: '1:183089429196:android:1538725084b2746c86e069',
    messagingSenderId: '183089429196',
    projectId: 'ncuber',
    storageBucket: 'ncuber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRBleZ2G2E2TjFiKckWKzOLpw1F7qRCU',
    appId: '1:183089429196:ios:7c5911121f29f2e686e069',
    messagingSenderId: '183089429196',
    projectId: 'ncuber',
    storageBucket: 'ncuber.appspot.com',
    iosClientId: '183089429196-us4i4m87tkmtdsetk5c0gg3klh6f8s7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ncuber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiRBleZ2G2E2TjFiKckWKzOLpw1F7qRCU',
    appId: '1:183089429196:ios:7c5911121f29f2e686e069',
    messagingSenderId: '183089429196',
    projectId: 'ncuber',
    storageBucket: 'ncuber.appspot.com',
    iosClientId: '183089429196-us4i4m87tkmtdsetk5c0gg3klh6f8s7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.ncuber',
  );
}
